apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-12
  namespace: k-att-y70-dev
  labels:
    app: mi-app-12
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-12
  template:
    metadata:
      labels:
        app: mi-app-12
    spec:
      containers:
        - name: contenedor-principal
          image: boriscutos/segundodeploy:build-{{ tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap-2
            - secretRef:
                name: mi-secret-2
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio-12
  namespace: k-att-y70-dev
spec:
  selector:
    app: mi-app-12
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap-2
  namespace: k-att-y70-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret-2
  namespace: k-att-y70-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==   # "hola2" en base64, ejemplo
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa-2
  namespace: k-att-y70-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment-12
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc-v12
  namespace: k-att-y70-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
